.SUFFIXES:

     PROJECT_ROOT := ../../../cpp
     MAINPROG_DIR := ../

include $(PROJECT_ROOT)/allg/makerules/Makefile.lib
include Makefile.prj
include $(PROJECT_ROOT)/allg/makerules/Makefile.def
include $(PROJECT_ROOT)/allg/makerules/Makefile.rul
    include Makefile.dep


