#!/bin/bash

hub-tool login puran2

if [ "$1" = "" ]; then
  exit 0
fi

for tag in $1
do
  hub-tool tag rm -f puran2/database:$tag
  hub-tool tag rm -f puran2/erp-init:$tag
#  hub-tool tag rm -f puran2/erp-server:$tag
#  hub-tool tag rm -f puran2/sbs-apache:$tag
done

