#!/bin/bash 

origdb=erpdborig
orighost=localhost
origport=5432
origuser=admindb
#origpass='geheim'

checkdb=erpdb
checkhost=localhost
checkport=5432
checkuser=admindb
#checkpass='geheim'

if [ "$(id -u)" = "0" ]; then
    orighost=127.0.156.1
    checkhost=127.0.156.1
fi

cus_schemas="$cus_schemas
mne_hoai
mne_builddiary
mne_sabredav
mne_repository
mne_mail
mne_fixture
mne_shipment
mne_warehouse
mne_personnal
mne_crm
mne_base"

if [ -f dbcfg ]; then
    . dbcfg
fi

cd ../../dbsync;
. dbupdate
