#!/bin/sh

pid=$$
# exec 2> /tmp/$$.stderr

prefix=default
while [ $# -gt 1 ] ; do
  case $1 in
    -uowncompanyownprefix)  prefix=$2; shift 2;;
     *)                                shift 1;;
  esac
done

if [ "$prefix" = "" ]; then 
    prefix=default
fi

export TEXINPUTS=.:$PWD/../../entwicklung/tex/$prefix////:$PWD/../../entwicklung/tex/default////:$PWD/../../tex///:
export TEXMFVAR=$PWD/.texmf-var
export PATH=/opt/Tex/bin:/usr/texbin:/usr/bin:$PATH

cp $1 /tmp/$pid.tex
latex -output-directory=/tmp --output-format=dvi /tmp/$pid.tex
latex -output-directory=/tmp --output-format=dvi /tmp/$pid.tex
dvipdfm -o $1 /tmp/$pid.dvi

#cp /tmp/$pid.tex /tmp/debug.tex
#cp /tmp/$pid.log /tmp/debug.log
#cp /tmp/$pid.dvi /tmp/debug.dvi

rm /tmp/$pid.tex
rm /tmp/$pid.out
rm /tmp/$pid.dvi
rm /tmp/$pid.log
rm /tmp/$pid.aux

exit 0
